apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-node-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-node
  template:
    metadata:
      labels:
        app: frontend-node
    spec:
      containers:
        - name: frontend-node-container
          image: mayank750703/frontend-node:v1
          ports:
            - containerPort: 3000

  strategy:
    canary:
      abortScaleDownDelaySeconds: 5
      maxSurge: 50%
      maxUnavailable: 0

      steps:
        - setWeight: 50

      # ⭐ Add it HERE
      scaleDownActivenessProbe:
        httpGet:
          path: /
          port: 3000
